title: "Automation Test Report"
fonts:
  regular: "C:/Windows/Fonts/arial.ttf"
  bold: "C:/Windows/Fonts/arialbd.ttf"
  italic: "C:/Windows/Fonts/ariali.ttf"
  bolditalic: "C:/Windows/Fonts/arialbi.ttf"
